baseURL = "example.com"
languageCode = "en-us"
title = "小惡魔 - 電腦技術 - 工作筆記 - AppleBOY"
theme = "beautifulhugo"

metaDataFormat = "yaml"
# pygmentsStyle = "trac"
# pygmentsUseClassic = true
# pygmentsUseClasses = true
# pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true
#pygmentOptions = "linenos=inline"
disqusShortname = "appleboy48"
googleAnalytics = "UA-5766319-6"
enableRobotsTXT = true

[Params]
  homeTitle = " " # Set a different text for the header on the home page
  # subtitle = "美食日記，生活日記，電腦筆記"
  mainSections = ["post","posts"]
  logo = "https://lh3.googleusercontent.com/Kq9CxHZWopKj__EgF_BpzLv8FhwvDkc0iacrl9V5IJjpr-dZ7Y5O-Vc1i9FhGQ8gHTdKeBisG_1ie1IONQXmK0a3myyl_BNouP76CLHGHRzsPPRgRF3RiKYqOkdS86mZOIu7KYFTUio=w1920-h1080" # Expecting square dimensions
  favicon = "https://lh3.googleusercontent.com/Kq9CxHZWopKj__EgF_BpzLv8FhwvDkc0iacrl9V5IJjpr-dZ7Y5O-Vc1i9FhGQ8gHTdKeBisG_1ie1IONQXmK0a3myyl_BNouP76CLHGHRzsPPRgRF3RiKYqOkdS86mZOIu7KYFTUio=w1920-h1080"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  # useHLJS = true
  socialShare = true
  delayDisqus = true
  toc = true
  showRelatedPosts = true
  # hideAuthor = true
  gcse = "003841896160749976666:l9i5hqttpqi" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "https://lh3.googleusercontent.com/HWckAUZlHgbgrA--s-vhAzSKG4xZ_WW-c1tFjApEnZwK7DW4Vbma5zludB6F0z9aL9QQSvtNznJD4hSg6RnQo3JEyzcqUc3kDN_0jMj-hSOzHWRaMdScLc6BcyZDp_rcx3UqikIhbTQ=w1920-h1080"
  desc = "兩個寶貝"

[[Params.bigimg]]
  src = "https://lh3.googleusercontent.com/mHuLPVnaJQ29yL41niC7wbh1SFz_dJ1EdVKsUSreXELyhs0XtrQIYrBLhUI3VuI0wXkdTZO8bwpAvrOtiTtBx4UX7WIcTT6VzvL0ioLIfNhh_drk8WFxtisLFklIwDoTPiUYYgudLg0=w1920-h1080"
  desc = "演講照片"

[[Params.bigimg]]
  src = "https://lh3.googleusercontent.com/oC9TXlSqbMFJISiqhMYZHrYFot1hU8m6bqTvZEF37eEJB-c8uBbhJmZFubnmzy9W3DvVHONNXl-Nup9xWGV_U5vZ7RwaXzwAXWY-hjZuG8UmRBejxH6dGqdI4dY8jnKZaPr0iL6_He8=w1920-h1080"
  desc = "聯發科技"

[[Params.bigimg]]
  src = "https://lh3.googleusercontent.com/EuXHlo4U9TILoihH5i96VlY43ENvLjtDwaT0dcXOqIXoJZOqSvegmgydjDRyXybCjXsrEj9OGZcFooaGgFu6P0uKes-JS8FUxsV-vhPTESg0PpHaDBpqIzhMMs7uTp9ZiP8MshoxbGo=w1920-h1080"
  desc = "2015-02-27 結婚照"

[[Params.bigimg]]
  src = "https://lh3.googleusercontent.com/meNxGvRzhs4M4lTKqQGkY91za-Sp9hrjK5pYpwqgxcdmpVC57w5PVCsGDQ43mNKP8Q1ijAs2eZelcfu5Ci874xf0c44SQHIjefMoJB-dClUVybJ7bOeFZJk9ux6onZkGLpzBUIO6W_4=w1920-h1080"
  desc = "2015-02-27 結婚照"

[[Params.bigimg]]
  src = "https://lh3.googleusercontent.com/gfwyrMB0pCcChGfqDxYaQljrDXnlXLYY2-xtFXARG_tAzwcvxDJQGHZ-gxhMJ4EwLn1ojWghb_Y2u40MEpVXdXm1bKP2jyxnRsx_pfsimEmfnS_B1sRDsOAG_aHwP_6ywmqrQPfyT68=w1920-h1080"
  desc = "2015-02-27 家庭照"

[Author]
  name = "Appleboy"
  website = "https://blog.wu-boy.com"
  email = "appleboy.tw@gmail.com"
  facebook = "appleboy46"
  github = "appleboy"
  gitlab = "appleboy"
  bitbucket = "appleboy"
  twitter = "appleboy"
  linkedin = "appleboy"
  youtube = "channel/UCLCZJ9d_I7UJP2bpXpge8KA" # or channel/channelname

[[menu.main]]
    name = "Youtube 頻道"
    url = "http://bit.ly/youtube-boy"
    pre = '<i class="fab fa-youtube"></i>'
    weight = 1

[[menu.main]]
    identifier = "course"
    name = "線上課程"
    pre = '<i class="fas fa-video"></i>'
    weight = 2

[[menu.main]]
    parent = "course"
    name = "Go 語言基礎實戰"
    url = "/golang-online-course/"
    weight = 1

[[menu.main]]
    parent = "course"
    name = "Docker 容器開發實戰"
    url = "/docker-devops/"
    weight = 2

[[menu.main]]
    parent = "course"
    name = "一天學會 DevOps 自動化流程"
    url = "/drone-devops/"
    weight = 3

[[menu.main]]
  name = "歷年文章"
  pre = '<i class="fas fa-sitemap fa-lg"></i>'
  url = "/archives/"
  weight = 3

[[menu.main]]
    name = "文章標籤"
    pre = '<i class="fas fa-tags fa-lg"></i>'
    url = "/tags/"
    weight = 4

[[menu.main]]
  name = "文章分類"
  pre = '<i class="fas fa-sitemap fa-lg"></i>'
  url = "/categories/"
  weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 2
  [markup.tableOfContents]
    startLevel = 1

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
