name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Create cname file
        run: echo "demo.gh.wu-boy.com" > static/CNAME

      - name: Replace domain name
        run: sed -i.bak -e 's|http://example.com|https://demo.gh.wu-boy.com|g' config.toml

      - name: Update robot.txt
        run: |
          echo -e "User-agent: *\nDisallow: /" > static/robots.txt
          cat static/robots.txt

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
